apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: nekocafe
    environment: {{ .Values.global.environment }}
data:
  appName: {{ .Values.configMap.appName | quote }}
  logLevel: {{ .Values.configMap.logLevel | quote }}
  corsAllowedOrigins: {{ .Values.configMap.corsAllowedOrigins | quote }}
  environment: {{ .Values.global.environment | quote }}
